name: Publish Package

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Write .npmrc file
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > $HOME/.npmrc
          echo @rundown-studio:registry=https://npm.pkg.github.com >> $HOME/.npmrc

      - name: Install Dependencies
        run: npm ci --loglevel=error

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Compile Typescript
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - name: Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Write .npmrc file
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > $HOME/.npmrc
          echo @rundown-studio:registry=https://npm.pkg.github.com >> $HOME/.npmrc

      - name: Install Dependencies
        run: npm ci --loglevel=error

      - name: Run Unit Tests
        run: npm run test:ci
        env:
          NODE_OPTIONS: --experimental-vm-modules

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - name: Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

